### ISSUE TITLE
Clicking X too soon causes app to shutdown immediately

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/smapp#502] opened 2020-04-29 17:52 UTC
**Describe the bug**

Sometimes, clicking the X at the top right corner to close the app causes it to shutdown immediately.

**To Reproduce**
1. Run app. It's working fine.
1. go-spacemesh process dies (in my case, due to time sync issue) and app displays 'waiting for smesher status'
1. Shut down the app (click X then 'quit' on confirmation popup)
1. Reopen app
1. Unlock
1. Immediately click X - app shuts down immediately with no confirmation popup (before 'Syncing the mesh...' appears). Underlying go-spacemesh process appears to be suddenly killed.

**Expected behavior**
Expected the confirmation popup to appear so I could background the app

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by lrettig** [comment] 2020-05-01 21:44
This appears to happen anytime the app doesn't display the green "synced" status bar

**Comment by avive** [comment] 2020-05-04 05:37
The cause of this is that the app is currently configured to confirm quitting only is smeshing is setup and it assumes it is not setup yet. @IlyaVi - maybe the fix is to observe if smeshing is setup by examining local storage and without waiting for smeshing status.

**Comment by lrettig** [comment] 2020-05-04 20:58
> the app is currently configured to confirm quitting only is smeshing is setup and it assumes it is not setup yet

I don't think the app should ever kill the node outright upon quit. If there is any go-spacemesh process running, the prompt should appear.

**Comment by IlyaVi** [comment] 2020-05-17 09:15
after major changes made to the app, the quit dialog will appear any time when smeshing was set as per flag in app local storage. So even if X is clicked too soon - if there is smeshing user will see the dialog.
fixed in #495

**Closed by IlyaVi** 2020-05-17 09:15 UTC
Labels: bug
