### ISSUE TITLE
Force terminated while round finish timing.

### ISSUE THREAD

**Issue by hryksbt** [spacemeshos/smapp#1466] opened 2023-08-21 04:15 UTC
### Environment

* Smapp version: 1.0.18
* OS: Windows 10 | Ubuntu 22

### Describe the bug

Smapp was forced to terminate before and after the end of Round 1.
This also occurred during Round0 end timing too.
Nodes that were forced to exit at the time of Round 0 were unable to earn rewards for a long time.

### Question

In the 12 hours between Round 1 and Round 2, can a forced-out Smapp also complete the Proof and earn a reward?

### Steps to reproduce

1.  Just running Smapp.

### Expected behavior

Never stop and get rewards 100% fine.

### Actual behavior

Forced termination without notice. Then no rewards during round1.

### Screen shot

State at startup to forced termination.

<img width="568" alt="スクリーンショット 2023-08-21 10 19 35" src="https://github.com/spacemeshos/smapp/assets/2483747/df6039a0-379d-469c-aca4-8d1a72d5ae56">

### Logs

[log.txt.zip](https://github.com/spacemeshos/smapp/files/12391728/log.txt.zip)

### How to fix 

No idea.

**Comment by hryksbt** [comment] 2023-08-21 11:24
I faced below error too.
Seems totally unstable.

Log
[log2.txt.zip](https://github.com/spacemeshos/smapp/files/12395408/log2.txt.zip)

Screenshot
![スクリーンショット 2023-08-21 20 16 10](https://github.com/spacemeshos/smapp/assets/2483747/d3bad82b-2fc4-426d-bbae-055d87d4f79f)

**Comment by hryksbt** [comment] 2023-08-25 04:14
No one check this?

**Comment by hryksbt** [comment] 2023-09-04 07:20
Dear developers,
Could you check log and recognize problem?
Then I wish update.

**Comment by brusherru** [comment] 2023-09-25 16:40
Oops. Missed this one.
I think this is the duplicate of https://github.com/spacemeshos/smapp/issues/1490, right?
Then I'm closing the issue. If I miss something — feel free to correct me and reopen an issue :)

**Closed as completed by brusherru** 2023-09-25 16:40 UTC
