### ISSUE TITLE
Get rid of blinking on Node screen while progress updates

### ISSUE THREAD

**Issue by brusherru** [spacemeshos/smapp#812] opened 2021-10-06 21:47 UTC
### Environment
* Smapp version: https://github.com/spacemeshos/smapp/tree/post-gpu-setup

### Describe the bug
When Smapp creates PoS data and notifies GUI about its' progress, the whole Node screen blinks.

### Steps to reproduce
1.  Run Smapp (with working gpu-post)
2.  Start Smeshing with a big enough PoS data size to have time to check it out (E.G. >=4MB)
3.  See on Node screen

### Expected behavior
Progress updates. Nothing blinks, twitches and etc.

### Actual behavior
Progress updates, but the whole screen component blinks.

**Comment by avive** [comment] 2022-03-27 09:12
@brusherru is this fixed or still an open issue?

**Comment by brusherru** [comment] 2022-03-27 12:51
I have to check it, but I'm pretty sure that this is still actual. I didn't optimized rendering of that screen and components inside.

**Comment by maparr** [comment] 2022-08-01 09:11
hi @brusherru , will take this issue for work.

**Comment by maparr** [comment] 2022-08-14 09:03
@brusherru , right now cannot reproduce this issue, the Node screen is not blinking, can we close this issue?

**Closed as completed** 2022-08-25 11:28 UTC
Labels: bug, good first issue
