### ISSUE TITLE
Transaction Log Screen Content Overflow

### ISSUE THREAD

**Issue by avive** [spacemeshos/smapp#794] opened 2021-08-10 11:37 UTC
1. Minimize Smapp window size
1. Open transactions from wallet.

Result: activity view content overflows its area.
Expected: no overflow.

Possible fix: reduce the huge spacing between rows in this view so we don't need to adjust the min main windows size to fix this.

![Screen Shot 2021-08-10 at 2 37 25 PM](https://user-images.githubusercontent.com/96002/128860405-d76b98ce-d0ad-445c-96d4-c7d83eb93ea5.png)

**Comment by brusherru** [comment] 2021-08-16 22:51
Duplicate of https://github.com/spacemeshos/smapp/issues/772

**Closed as completed by brusherru** 2021-08-16 22:51 UTC
Labels: bug
