### ISSUE TITLE
No new smeshing rewards are displayed after some time

### ISSUE THREAD

**Issue by avive** [spacemeshos/smapp#834] opened 2021-12-12 11:30 UTC
### Environment
Smapp version 0.2.0 beta0

### Describe the bug

After being open for a long time, no new rewards are displayed.

### Steps to reproduce
1. Setup smeshing and observe rewards displayed in txs log.
2. Leave App open until new rewards stop to appear in txs log. (For me it took ~48 hours).

### Expected behavior
Smeshing rewards to display in transaction log and in the transactions preview area in the wallet screen.

### Actual behavior
At some point, new rewards are no longer displayed. 
After Smapp restart all the rewards from the time rewards stopped being displayed until the most recent rewards are displayed as expected.

Speculation of the cause: maybe the rewards stream gets disconnected?

**Comment by brusherru** [comment] 2021-12-15 09:26
It might particularly depend on https://github.com/spacemeshos/go-spacemesh/issues/2977, since I don't get all the rewards via the stream even I have account balance updates. But If I rerun the App it will request for the query endpoint, which will show up all rewards well.

However, I've already caught and can confirm that some of the streams sometimes closes unexpectedly and can't be reopened. Will investigate it soon.

**Comment by avive** [comment] 2021-12-29 09:59
I don't see this anymore on testnet-021

**Comment by brusherru** [comment] 2022-01-03 08:59
So I'm closing it. If you can reproduce the bug, please reopen this issue.

**Closed as completed by brusherru** 2022-01-03 08:59 UTC
Labels: bug
