### ISSUE TITLE
Allow mesh data storage location to be changed

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/smapp#490] opened 2020-04-19 08:32 UTC
My Windows VM has very limited hard disk space in its main partition and I don't think I'll be able to fully sync the mesh, but I can't currently store this data in a different place/location.

**Comment by IlyaVi** [comment] 2020-05-17 09:17
@avive

**Comment by brusherru** [comment] 2022-02-02 12:02
@lrettig @avive I want to clarify, does flag `--data-folder` responsible for it?
If so the solution is to add optional selection (on Settings screen) of the data folder and store this value on fs.
And I assume that we should move the existing `node-data` folder to the new place before restarting the Node (to continue from the same place).
Am I right?

If so — I can easily reword it and then implement it quickly.

**Comment by brusherru** [comment] 2022-02-02 12:35
@lrettig is this issue some kind of a duplicate of #521?

**Comment by avive** [comment] 2022-03-30 10:32
@lrettig

**Comment by noamnelke** [comment] 2022-03-30 10:51
@brusherru yes, `--data-folder` is the arg you need to change and what you wrote about moving it is correct.

The other issue is weird. It should behave that way only if his home dir is `~/config` because the default data folder is `{USER_HOME_LOCATION}/spacemesh/`. However, it seems like the same issue.

**Closed** 2022-04-25 12:36 UTC
Labels: feature, P1
