### ISSUE TITLE
Feature: custom config folder location

### ISSUE THREAD

**Issue by whoabuddy** [spacemeshos/smapp#521] opened 2020-05-28 21:35 UTC
**Describe the Feature**

Installing the smapp on Linux generates a configuration folder under `~./config/Spacemesh`.

This folder quickly grows in size as the number of blocks increases, currently taking up ~750mb on my virtual machine running 0.0.12 (so far), and ~8.4gb from my previous installation of 0.0.7.

If I am using a SSD + HDD setup this could fill the system drive, and I would like to be able to redirect this folder to a new location.

**To Reproduce**

1. Install Smapp on Linux
2. Configure Smapp and sync with the mesh
3. Check size of `~./config/Spacemesh` folder

**Expected Behavior**

To have the ability to set a new location for this folder, ideally during the initial setup phase and/or from the settings menu. It could be an "advanced" or "custom" option as it doesn't apply to everyone.

**Screenshots**

![VirtualBox_SmeshLikeAMofo_28_05_2020_14_17_10](https://user-images.githubusercontent.com/9038904/83195368-f9b0de00-a0ee-11ea-9219-e904d84e1d6d.png)

**Desktop (please complete the following information):**

 - OS: Ubuntu Desktop 20.04 LTS

**Additional Context**

None.

**Comment by brusherru** [comment] 2022-04-12 12:03
Duplicate of #490

**Closed by brusherru** 2022-04-12 12:03 UTC
Labels: feature, P1
