### ISSUE TITLE
Memory leak after running for few hours. App shows an error and in the console:

### ISSUE THREAD

**Issue by avive** [spacemeshos/smapp#336] opened 2020-02-01 21:43 UTC
> smapp@0.0.1 start-main-dev /Users/avive/dev/smapp
> cross-env HOT=1 NODE_ENV=development electron -r @babel/register ./desktop/main.dev.js

^[(node:9723) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 GET_ACCOUNT_REWARDS_RESPONSE listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit
(node:9723) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 GET_ACCOUNT_REWARDS_RESPONSE listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit

**Comment by IlyaVi** [comment] 2020-02-03 16:58
duplicate of #335

**Closed by IlyaVi** 2020-02-03 16:58 UTC
Labels: bug
