### ISSUE TITLE
When I open Smapp it has a white screen 5 seconds after starting

### ISSUE THREAD

**Issue by travjzx** [spacemeshos/smapp#1548] opened 2023-10-06 12:50 UTC
Description

When I try to start smapp after updating to 1.2.1 on Linux x64 it works for 5 seconds then the app screen goes white and I can't see anything.

Steps to reproduce

Open smapp 1.2.1 and then it goes white after 5 seconds
Actual Behavior

White screen after 5 seconds

Expected Behavior

Rolling back to 1.1.11 it appears to function correctly

Environment

Please complete the following information:

OS:
Linux x64
Node Version:
1.2.1
Additional Resources

I noticed it was a bug on a different OS in a closed ticket previously.

**Comment by brusherru** [comment] 2023-10-06 14:05
The issue is fixed in https://github.com/spacemeshos/smapp/pull/1544
You can download this pre-release: https://github.com/spacemeshos/smapp/releases/tag/v1.2.1-electron.25.8.4
Or wait for an official release with the mentioned fix.

**Closed as completed by brusherru** 2023-10-06 14:05 UTC

**Comment by xusanduo08** [comment] 2023-10-08 09:20
Me too. I had to degrade
