### ISSUE TITLE
Smapp 1.2.1 fails on Ubuntu 22.04.3 LTS

### ISSUE THREAD

**Issue by username-rand** [spacemeshos/smapp#1550] opened 2023-10-08 13:46 UTC
### Environment

* Smapp version: 1.2.1
* Node version: v1.1.6
* OS: Ubuntu 22.04.3 LTS
### Describe the bug

Both 1.2.1 Smapp dpkg version and AppImage version fail on Ubunut 22.04.3 LTS.   Previously using 1.1.9 which works.

/Spacemesh-1.1.9.AppImage
[1675836:1007/152409.188735:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.InvalidArgs: No such interface “org.freedesktop.portal.FileChooser”
[1675836:1007/152409.188759:ERROR:select_file_dialog_linux_portal.cc(242)] Failed to read portal version property
[1675879:1007/152438.968395:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[1675879:1007/152519.021230:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!

### Steps to reproduce

1.  I usually use the dpkg version.  After updating with dpkg that version failed.
2. Next I started the 1.1.9 version of AppImage (which I had) and let it update itself to 1.2.1.  After updating that application also failed.

Just start the Application and log in.  After logging in the screen turns white (blank).

### Actual behavior
Application failed.

### Logs (Have restarted 1.1.9.)

Here is the Applications error output from AppImage :

/Spacemesh-1.1.9.AppImage
[1675836:1007/152409.188735:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.InvalidArgs: No such interface “org.freedesktop.portal.FileChooser”
[1675836:1007/152409.188759:ERROR:select_file_dialog_linux_portal.cc(242)] Failed to read portal version property
[1675879:1007/152438.968395:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[1675879:1007/152519.021230:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!

### How to fix 

Dont know how to fix.  Reverted back to 1.1.9 which works.

**Comment by maparr** [comment] 2023-10-09 09:53
Hi @username-rand , thank u for the opened issue.

The issue is fixed in https://github.com/spacemeshos/smapp/pull/1544
You can download this pre-release: https://github.com/spacemeshos/smapp/releases/tag/v1.2.1-electron.25.8.4
Or wait for an official release with the mentioned fix.

**Closed as completed** 2023-10-09 09:53 UTC
