### ISSUE TITLE
specify target directory for blockchain data

### ISSUE THREAD

**Issue by willemsFEB** [spacemeshos/smapp#895] opened 2022-04-22 14:22 UTC
In smapp on Linux, when setting up spacemesh, you can't specify the target directory for the blockchain data, and it will default to ~/.config/spacemesh . For devices with low internal storage it would be useful to be able to specify the target directory for blockchain data, eg an external drive.

**Comment by brusherru** [comment] 2022-04-23 13:25
Hello @willemsFEB,
Thanks for the suggestion and for sharing your pain.

I have good news for you: It is already almost done in #894!
You can check it out or wait for the next release, this feature will be in.

Since this is a duplicate of #490 and #521, I'm closing the issue. ✌️

**Closed as completed by brusherru** 2022-04-23 13:25 UTC

**Comment by willemsFEB** [comment] 2022-04-25 08:39
Thanks! Very excited to test it out! Sorry for the duplicate ticket
