### ISSUE TITLE
App indicated post is not setup

### ISSUE THREAD

**Issue by avive** [spacemeshos/smapp#445] opened 2020-03-20 20:33 UTC
Synced 0.1.7 node in 0.0.4 App.
Smeshing has been setup in the app.
Node is fully synced and smeshing has been set up.

In logs on app startup:
`2020-03-20T22:29:34.894+0200	INFO	6bde3.atxBuilder   	PoST initialization completed	{"node_id": "6bde3", "datadir": "/Users/avive/Documents", "space": "4294967296", "commitment merkle root": "31e31ed5eb9f5103c54466a67aa18fc9ab40fbcaf515e45fba922ab420d90fcb"}
2020-03-20T22:29:34.894+0200	INFO	6bde3.atxBuilder   	using existing atx challenge	{"node_id": "6bde3", "epoch_id": 1}`

Result: app prompts user to setup smeshing.
Expected: app to indicate smeshing has been setup.

**Comment by avive** [comment] 2020-03-20 20:38
Here's the log file. If logging is insufficient to resolve this issue then we should add more logging to this flow.
 
[spacemesh-log.txt.zip](https://github.com/spacemeshos/smapp/files/4361721/spacemesh-log.txt.zip)

**Comment by IlyaVi** [comment] 2020-04-05 08:15
close as duplicate of #411

**Closed by IlyaVi** 2020-04-05 08:15 UTC
Labels: bug, testnet
