### ISSUE TITLE
App that is minimized/running in the background cannot be opened from tray (v0.0.6RC4)

### ISSUE THREAD

**Issue by yaelmhoffman** [spacemeshos/smapp#471] opened 2020-03-31 13:14 UTC
Version: v0.0.6RC4, v0.0.6RC5
OS: Windows 10 home, Windows 10 Pro.
Computer used for testing: Spacemesh lab 1, ASUS notebook.

**Expected:**
User selects ‘run in background’ after clicking the exit button of the application. App is minimized and a spacemesh icon appears in the tray. User left clicks on icon in tray, and the app reopens.

**Actual:**
User left clicks on icon in tray, and nothing happens, even after repeated attempts.

**Repro steps:**
1. Uninstall application and make sure no spacemesh processes are running.
2. Install app from scratch.
3. Set up wallet and smeshing.
4. When app indicates it is actively smashing, exit, and select ‘run in background’.
5. Click on icon in tray.

Note: The user can open the app by right clicking and selecting 'show app', but a normal left click does nothing.

**Comment by IlyaVi** [comment] 2020-04-01 09:58
Can't reproduce on lab1 and mac os

**Comment by yaelmhoffman** [comment] 2020-04-01 13:45
Can still reproduce in build v.0.0.6RC5. Please see video:
https://files.slack.com/files-pri/T6AU7S14G-F01179NLAAU/20200401_162521_1_.mp4

**Comment by avive** [comment] 2020-04-01 13:48
To clarify, app should be opened on single-click and on double click on the tray icon like most windows tay icons behave. Currently it is only accessible from the tray icon menu on right-click.

**Comment by IlyaVi** [comment] 2020-05-17 09:48
fixed in #495

**Closed by IlyaVi** 2020-05-17 09:48 UTC
Labels: enhancement, testnet
