### ISSUE TITLE
"14 Unavailable - connection dropped error" message

### ISSUE THREAD

**Issue by antonlerner** [spacemeshos/smapp#855] opened 2022-01-17 10:24 UTC
### Environment

* Smapp version: 0.2 | testenet216
* Node version: v0.2 testenet216
* OS: unknown

### Describe the bug
![image](https://user-images.githubusercontent.com/21037839/149751306-45b8b0a0-219b-4335-ae67-a9ed62d6649e.png)

User received "14 Unavailable - connection dropped error" on proof of space generation screen

### Steps to reproduce
Run first time initialisation - get to post generation screen

### Expected behavior
Post should be generates

### Actual behavior
Got error "14 Unavailable - connection dropped error"

### Logs

Attach `app-logs.txt` and `spacemesh-log.txt`

If you can find out the part of the logs that relates to the problem, attach them or paste in code-block.

If you have an idea of how the bug can be fixed, provide a short description.

**Comment by brusherru** [comment] 2022-01-17 11:24
@antonlerner please, fulfill the "Logs" section and add other details if possible:
- is node syncing / synced now?
- can you also attach `node-config.json` (from the same directory: `%APPDATA%/Spacemesh`)? Or at least copy-paste a part with key `smeshing`?
- restarting the app fixes the problem?
- what happens when you click on the "resume" button? Nothing?

**Comment by antonlerner** [comment] 2022-01-19 13:19
![image](https://user-images.githubusercontent.com/21037839/150138681-82b11f90-5e51-4380-9d71-acc4aebcdd8d.png)

**Comment by avive** [comment] 2022-03-27 08:48
@antonlerner - can you please provide more info about this issue so we can try to repo?

**Comment by oriya** [comment] 2022-07-04 08:14
@brusherru Can we close this?

**Comment by maparr** [comment] 2022-07-05 08:54
the issue is not relevant anymore.

**Closed as completed by maparr** 2022-07-05 08:54 UTC
Labels: bug
