### ISSUE TITLE
Windows Uninstall leaves data behind in registry and in file system.

### ISSUE THREAD

**Issue by avive** [spacemeshos/smapp#499] opened 2020-04-27 16:02 UTC
Uninstall Spacemesh using the Windows Uninstaller.

Result: Spacemesh data left in registry and in file system.

Expected: don't leave a trace behind :-)

**Comment by brusherru** [comment] 2022-02-02 12:44
#635 seems like a bug report for this issue

**Comment by maparr** [comment] 2022-04-26 18:28
Hey @avive 
in the current version of smapp seems we don't have this issue 
1. if delete the Spacemesh folder in Program Files in Windows, and run the installer again, the installation process will go smooth and will ask you to sign in to the account and enter the password ( because we didn't remove the data folder )
2. in case of the default uninstall process from Windows programs manager, working as expected, clean up the data and the Spacemesh folder, after this process u will be able to sign in/sing up
3.  in case of the default uninstall process from the Spacemesh app through reinstall app in settings, working as expected, clean up the data and the Spacemesh folder, after this process u will be able to sign in/sing up

**Comment by brusherru** [comment] 2022-07-06 00:09
Since we can not reproduce the bug we're closing the issue.
If someone will face it again — please reopen this issue or file a new one.

**Closed by brusherru** 2022-07-06 00:09 UTC
Labels: bug, P1, on-hold
