### ISSUE TITLE
Timestamp missing for rewards

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/smapp#520] opened 2020-05-27 18:08 UTC
**Describe the bug**

I see a timestamp for incoming SMH tx, but not for smeshing rewards, both on the wallet and smeshing screens. I also only see two rewards on the wallet screen.

**To Reproduce**
1. Launch a new node, connect to new testnet (net id 115)
1. Start smeshing and collecting rewards
1. Receive an incoming tx from the tap

**Expected behavior**
I expect to see timestamps on all rewards, and to see the same list of rewards on both wallet and smeshing screens.

**Screenshots**
Below

**Desktop (please complete the following information):**
 - OS: Linux
- app version: 0.0.12

**Additional context**
![image](https://user-images.githubusercontent.com/3316532/83056327-32838100-a023-11ea-9c92-1f1def12b777.png)
![image](https://user-images.githubusercontent.com/3316532/83056357-3e6f4300-a023-11ea-999f-a58011dd06f2.png)

**Comment by IlyaVi** [comment] 2020-05-28 10:03
duplicate of #517

**Closed** 2020-05-28 10:06 UTC
